
modLoader="javafml" #mandatory

loaderVersion="[40,)"

license="All rights reserved"

issueTrackerURL = "https://github.com/MehVahdJukaar/snowyspirit/issues"


[[mods]] #mandatory
    modId="snowyspirit" #mandatory

    version="${version}" #mandatory

    displayName="Snowy Spirit" #mandatory

    displayURL = "https://www.curseforge.com/minecraft/mc-mods/snowy-spirit" #optional

    logoFile="icon.png" #optional

    credits="MehVahdJukaar, Plantkillable" #optional

    authors="MehVahdJukaar" #optional

    description='''
    Winter themed mod that adds working sleds and winter related items with related ai tweaks for villagers
    '''

[modproperties.snowyspirit]
    catalogueItemIcon = "snowyspirit:sled_oak" #catalogue icon
    configuredBackground = "snowyspirit:textures/blocks/gingerbread_frosted_block.png"

[[dependencies.snowyspirit]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.snowyspirit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowyspirit]]
    modId="moonlight"
    mandatory=true
    versionRange="[1.20-2.5.3,)"
    ordering="NONE"
    side="BOTH"
